### ISSUE TITLE
Need for a new C77 code for videos taken from ROV, observatories, moorings, etc. (BODCNVS-1247)

### ISSUE THREAD

**Issue by SismerND** [nvs-vocabs/C77#1]
We need to have a code for videos in C77 list (videos taken from ROV, observatoring, moorings, ...)

**Comment by gwemon** [comment]
@SismerND thank you for your request and apologies for not following this up sooner. As far as I can see, the only term that we have in C77 that relates to visual data acquisition is ["Bottom photography"](http://vocab.nerc.ac.uk/collection/C77/current/G08/) which was inherited from the original ROSCOP vocabulary.
We clearly need a term that covers video data acquisitions but also other types of visual data acquisitions (i.e. not just seabed facing ones). What would be the best option? To create a term that would cover any visual data acquisition? or is there a reason why we should separate video from still image acquisition? Videos and still images could potentially be taken for a very broad range of purposes including benthic flora/fauna biodiversity, survey of underwater man-made structures, they could also be taken within the water column or above the water column (e.g. sea state, bird and mammal observations etc).  Is it okay to lump all these together? Also if we did that shall we deprecate "Bottom photography"?   
C77 is a controlled vocabulary for shipboard activities. Is there a need to be more specific about the type of visual observations based on the horizon studied?  
The new term would be linked to the L05 term for "Cameras" (http://vocab.nerc.ac.uk/collection/L05/current/311/) which was defined as a broad term to cover any visual data acquisition equipment and a number of platforms in L06 (http://vocab.nerc.ac.uk/collection/L06/current/).
Let me know if you have preferences related to these questions. I am going to invite the sdc-tech governance group to advise.

**Comment by roy-lowry** [comment]
Hi Gwen,
You can't remove bottom photography from C77. It's such a fine example when giving talks about what vocabularies lead people to believe happens on cruises :-)) Seriously, deprecating from C77 isn't a good idea because of its long history in cruise metadata extending back into paper records. that can never be covered by automated substitution. 
I have also discouraged attempts in the past to extend C77 to provide a cruise activity vocabulary that is more fit for purpose because it has such glaring design flaws that it's like building on quicksand. A fresh start using C77 as reference material is a much better idea. However, I have added a couple of concepts where the extension either plugged obvious gaps or covered activities that weren't thought of when C77 was designed PROVIDING the new concepts have a similar granularity to the existing concepts.  Making the granularity finer is a slippery slope that can only end in tears.
With this request I can see two gaps that could be covered by acceptable (to me) new C77 terms which are 'ROV deployments' and 'Water column photography'. 'Above surface photography' is another gap at existing granularity that your questions have identified. Remember that the primary CSR application allows multiple C77 concepts to be linked to a single activity. For example, you could have 'Bottom photography' and 'Zoobenthos'.  I feel that differentiating video and still photography would be a fining of granularity heading down that slippery slope I mentioned above.
Cheers, Roy.

**Comment by gwemon** [comment]
Thanks @roy-lowry
So we identified 3 new terms to be added to C77:
'ROV deployments' with description: "Shipboard activity identifying the deployment of Remotely Operated Vehicles." 
'Water column photography' with description: "Shipboard activity identifying the capture of still and moving images of water column photography using any kind of photographic equipment.'
'Above surface photography': "Shipboard activity identifying the capture of still and moving images above the water surface using any kind of photographic equipment.'

Then we have also receive a new request for underwater sound recordings (see https://github.com/nvs-vocabs/C77/issues/2).

**Comment by danibodc** [comment]
@gwemon @roy-lowry 
Is it also worth including AUV and USV deployments? Either as separate terms or grouped together with ROVs, called something like 'Robotic vehicle deployments' or similar? Description could be "Shipboard activity identifying the deployment of Remotely Operated Vehicles, Autonomous Underwater Vehicles or Unmanned Surface Vehicles."

USVs may not be deployed from a ship in all cases however, so would be interested to hear your thoughts.

**Comment by roy-lowry** [comment]
@danibodc No problem with their being included in a broader term as you suggest/define. 

I would be concerned were they to be separate C77 terms. The purpose of C77 is to describe shipboard activities so it's of no consequence that USVs can be deployed other than from ships. It's perfectly possible to deploy a CTD from a pier.

**Comment by danibodc** [comment]
3 new C77 terms loaded, they will be live on the NVS from tomorrow morning:

R01 - Water column photography
R02 - Above surface photography
R03 - Robotic vehicle deployments

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/C77/current/R01/
https://vocab.nerc.ac.uk/collection/C77/current/R02/
https://vocab.nerc.ac.uk/collection/C77/current/R03/
